version: '3'
services:
  web:
    image: php:7.4-apache
    ports:
      - "88:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:5.7
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: chuongmobile
      MYSQL_USER: phuctd
      MYSQL_PASSWORD: tranducphuc2003
      MYSQL_ROOT_PASSWORD: tranducphuc2003